branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: vitta2
  default_ec2_keyname: vitta2
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: null
